import type { Skills } from '@/types/skills';

export const skills: Skills = {
   technicalSkills: [
      { id: 13, name: 'Solidity' },
      { id: 14, name: 'Rust' },
      { id: 15, name: 'Yul' },
      { id: 6, name: 'Web3.js' },
      { id: 17, name: 'Ethers.js' },
      { id: 18, name: 'Wagmi' },
      { id: 19, name: 'Moralis' },
      { id: 20, name: 'DeFi Protocal' },
      { id: 21, name: 'OpenZeppelin' },
      { id: 1, name: 'JavaScript' },
      { id: 2, name: 'TypeScript' },
      { id: 3, name: 'React.js' },
      { id: 22, name: 'Next.js' },
      { id: 23, name: 'GraphQL' },
      { id: 24, name: 'Node.js' },
      { id: 25, name: 'Express.js' },
      { id: 26, name: 'Django' },
      { id: 27, name: 'RESTful API' },
      { id: 4, name: 'Redux Toolkit' },
      { id: 5, name: 'RTK Query' },
      { id: 6, name: 'RESTful APIs' },
      { id: 7, name: 'MongoDB' },
      { id: 8, name: 'PostgreSQL' },
      { id: 9, name: 'Tailwind CSS' },
      { id: 10, name: 'MySQL' },
      { id: 12, name: 'Stripe' },
      { id: 11, name: 'Docker' },
      { id: 12, name: 'AWS' },
   ],
   tools: [
      { id: 10, name: 'Hardhat' },
      { id: 11, name: 'Truffle' },
      { id: 12, name: 'Infura' },
      { id: 13, name: 'Alchemy' },
      { id: 14, name: 'Canche' },
      { id: 15, name: 'Anchor' },
      { id: 1, name: 'Git' },
      { id: 2, name: 'Webpack' },
      { id: 3, name: 'Vite' },
      { id: 4, name: 'Storybook' },
      { id: 5, name: 'Jest' },
      { id: 6, name: 'ESLint' },
      { id: 7, name: 'StyleLint' },
      { id: 8, name: 'Prettier' },
      { id: 9, name: 'CI/CD pipelines' },
   ],
};
